name: ClassifyWithCertainty
channels:
  - conda-forge
dependencies:
  - ipykernel=6.21.2
  - ipython=8.11.0
  - ipywidgets=8.0.4
  - jupyterlab=3.6.1
  - matplotlib=3.7.0
  - numpy=1.24.2
  - pandas=1.5.3
  - python=3.11.0
  - scikit-learn=1.2.1
  - scipy=1.10.1
  - seaborn=0.12.2
  - pip:
    - datasets=2.10.1
    - huggingface-hub=0.12.1
    - nvidia-cublas-cu11=11.10.3.66
    - nvidia-cuda-runtime-cu11=11.7.99
    - nvidia-cuda-nvrtc-cu11=11.7.99
    - nvidia-cudnn-cu11=8.5.0.96
    - sentencepiece=0.1.97
    - torch=1.13.1
    - torchtext=0.6.0
    - tqdm=4.64.1

